#!/bin/bash
FIRE_BOARD=ebf_imx_6ull_mini
LINUX=4.19.35
UBOOT=2020.10
DISTRIBUTION=Debian
DISTRIB_RELEASE=buster
DISTRIB_TYPE=console
INSTALL_TYPE=ALL
export FIRE_BOARD
export LINUX
export UBOOT
export DISTRIBUTION
export DISTRIB_RELEASE
export DISTRIB_TYPE
export INSTALL_TYPE
