name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: update
      run: sudo apt update
    - name: get app
      run: sudo apt install make gcc-arm-linux-gnueabihf gcc bison flex libssl-dev dpkg-dev lzop
      
    - name: setenv1
      run: sudo export FIRE_BOARD=ebf_imx_6ull_mini
    - name: setenv2
      run: sudo export LINUX=4.19.35
    - name: setenv3
      run: UBOOT=2020.10
    - name: setenv4
      run: sudo export DISTRIBUTION=Debian
    - name: setenv5
      run: sudo export DISTRIB_RELEASE=buster
    - name: setenv6
      run: sudo export DISTRIB_ARCH=armhf
    - name: setenv7
      run: sudo export DISTRIB_RELEASE=buster
    - name: setenv8
      run: sudo export INSTALL_TYPE=ALL
    - name: Make
      run: make 
    - name: Prepare artifact
      run: |
        mkdir -p ./artifact/firmware
        cp -rf $(find ./deploy/* -type f -name "*.img") ./artifact/firmware/
    - name: Deliver firmware
      uses: actions/upload-artifact@v2
      with:
        name: CLtest
        path: ./deploy
