name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    
    - name: update
      run: sudo apt update
    - name: get app
      run: sudo apt install make gcc-arm-linux-gnueabihf gcc bison flex libssl-dev dpkg-dev lzop
      
    - name: setenv
      run: ./env/ci.sh
        
    - name: Make
      run: make 
    - name: Prepare artifact
      run: |
        mkdir -p ./artifact/firmware
        cp -rf $(find ./deploy/* -type f -name "*.img") ./artifact/firmware/
    - name: Deliver firmware
      uses: actions/upload-artifact@v2
      with:
        name: CLtest
        path: ./deploy
